version: 2.1

orbs:
  node: circleci/node@lts

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: test
          command: yarn run test

workflows:
  build:
    jobs:
      - test
        
